# Generated by Django 5.1.1 on 2024-09-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glamping',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
