# Generated by Django 5.1.1 on 2024-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0002_glamping_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glamping',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.AddField(
            model_name='glamping',
            name='imagen2',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='glamping',
            name='imagen3',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='glamping',
            name='imagen4',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='glamping',
            name='imagen5',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='glamping',
            name='imagen6',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
