# Generated by Django 5.1.1 on 2024-09-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0003_rename_imagen_glamping_imagen1_glamping_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glamping',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='glamping',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='glamping',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='glamping',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='glamping',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='glamping',
            name='imagen6',
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/')),
                ('glamping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pag_admin.glamping')),
            ],
        ),
    ]
