# Generated by Django 5.1.1 on 2024-09-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0004_remove_glamping_imagen1_remove_glamping_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
