# Generated by Django 5.1.1 on 2024-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0007_alter_glamping_imagen1_alter_glamping_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamping',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
