# Generated by Django 5.1.1 on 2024-09-11 16:33

import pag_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0008_alter_glamping_imagen2_alter_glamping_imagen3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamping',
            name='imagen1',
            field=models.ImageField(upload_to=pag_admin.models.GlampingImagePath()),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to=pag_admin.models.GlampingImagePath()),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to=pag_admin.models.GlampingImagePath()),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen4',
            field=models.ImageField(blank=True, upload_to=pag_admin.models.GlampingImagePath()),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen5',
            field=models.ImageField(blank=True, upload_to=pag_admin.models.GlampingImagePath()),
        ),
        migrations.AlterField(
            model_name='glamping',
            name='imagen6',
            field=models.ImageField(blank=True, upload_to=pag_admin.models.GlampingImagePath()),
        ),
    ]
