# Generated by Django 5.1.1 on 2024-09-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0010_remove_reserva_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasOcupadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocupada', models.DateField()),
                ('glamping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_ocupadas', to='pag_admin.glamping')),
            ],
            options={
                'verbose_name': 'Fecha Ocupada',
                'verbose_name_plural': 'Fechas Ocupadas',
                'unique_together': {('glamping', 'fecha_ocupada')},
            },
        ),
    ]
