# Generated by Django 5.1.1 on 2024-09-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0011_fechasocupadas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechasOcupadas',
        ),
    ]
