# Generated by Django 5.1.1 on 2024-09-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0012_delete_fechasocupadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glamping',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='glamping',
            name='precio',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
