# Generated by Django 5.1.1 on 2024-09-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_admin', '0013_remove_glamping_ubicacion_glamping_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPayU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('transaccion_aprobada', models.BooleanField(default=False)),
                ('payu_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payu_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag_admin.cliente')),
                ('glamping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pag_admin.glamping')),
            ],
            options={
                'verbose_name': 'Transacción PayU',
                'verbose_name_plural': 'Transacciones PayU',
            },
        ),
    ]
